# Generated by Django 3.2 on 2021-05-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=30)),
                ('email', models.EmailField(db_column='Email', max_length=60)),
                ('contact', models.CharField(db_column='Contact_No', max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'None')], default='N', max_length=10)),
                ('usrStatus', models.BooleanField(db_column='Maritial Status')),
                ('age', models.IntegerField(db_column='Age')),
                ('date_of_journey', models.DateField(db_column='Date_Of_Journey')),
                ('seat', models.FloatField(db_column='Seat')),
                ('coach', models.TextField()),
                ('birthmark', models.TextField(db_column='Birthmark')),
                ('usrImg', models.ImageField(db_column='Usr_Img', upload_to='')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
